[green_agent]
agentbeats_id = "019bc42c-a4a9-74f1-98cc-6804c5dce0b2"  # Paste green agent ID here
env = { }

[[participants]]
agentbeats_id = "019bc430-5988-7a80-930b-7e08617c0a5e"  # Paste purple agent ID here
name = "purple_agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
#task_ids = [28777]  # Testing with single task
# Testing workflow - Added /tmp/rcabench volume mount for ARVO workspace v3
#task status compl
task_ids_file = "/app/successful_task_ids.txt"
num_tasks = 3
